---
title: 'ANÁLISIS ESPACIAL DE SISMOS EN LOS CANTONES DE COSTA RICA DURANTE EL PERIODO 2010-2022'
author:
- 'Camila Aguilar'
- 'Brenda Fonseca'
- 'Héctor Ramírez'
date: "Noviembre 2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Paquetes

```{r}
library(readxl)
library(dplyr)
library(lubridate)
library(stringr)
library(car)
library(sf)
library(ggplot2)
library(tidyr)
library(sp)
library(spData)
library(mapview)
library(spdep)
library(tmap)
```


# Procesamientos previos

```{r}
###Lectura de datos
datos <- read_excel("Datos/sismos_cr.xlsx")
```


```{r}
###Seleccionar solo las variables necesarias y renombrar algunas
datos2 <- datos %>% 
  dplyr::select(time, latitude, longitude,  PC, canton, descrp., mag, magError) %>% 
  rename(lon = longitude,
         lat = latitude,
         lugar = descrp.)
```


```{r}
##Dejar la fecha en la zona horaria para CR
datos2$fecha <- with_tz(datos2$time, tzone = "America/Costa_Rica")
```

```{r}
###Seleccionar variables
datos2 <- datos2 %>% 
  dplyr::select(fecha, lat:magError)
```



```{r}
###Crear variables de tiempo
datos2 <- datos2 |> mutate(
  anio = stringr::str_sub(fecha,1,4),
  mes = substr(as.character(fecha),6,7),
  dia = substr(as.character(fecha),9,10),
  fecha2 = as.Date(fecha))
```


```{r}
###Seleccionar variables
datos2 <- datos2 %>% 
  dplyr::select(fecha, fecha2, anio:dia, lat:magError)
```

```{r}
#### Trabajar solo con los sismos mayores a 2.9 (3 o más de magnitud)
datos2 <- datos2 %>% 
  filter(mag > 2.9)
```



```{r}
###Crear variable de clasificación para la magnitud
datos2$clas_n <- car::recode(datos2$mag,
                             "0=1; 3:3.9 = 2; 4:4.9=3; 5:5.9=4; 6:6.9=5; 7:7.9=6")

datos2$clas <- as.factor(datos2$clas_n)

levels(datos2$clas) <- c("Muy ligera", "Ligera", "Moderada", "Fuerte", "Muy fuerte")
```



```{r}
###Generar los conteos (variable de interés) por cantón
datos3 <- datos2 %>% 
  group_by(PC, canton) %>% 
  summarise(cantidad = n(),
            mag_prom = mean(mag))

###Crear variable de clasificación para la magnitud
datos3$clas_n <- car::recode(datos3$mag_prom,
                             "3:3.9999999999999 = 1; 4:4.9=2; 5:5.9=3; 6:6.9=4; 7:7.9=5")
datos3$clas <- as.factor(datos3$clas_n)

levels(datos3$clas) <- c("Muy ligera", "Ligera", "Moderada", "Fuerte", "Muy fuerte")
```




```{r}
###Códigos (PC) de los cantones
codigos <- read_excel("Datos/cod_cantones81.xlsx")

canton <- read_sf('Límites cantonales de Costa Rica/Cantones2014ctm05.shp')


###Seleccionar variables de interés
canton <- canton %>% 
  dplyr::select(NCANTON, CODNUM, geometry) %>% 
  arrange(CODNUM) %>% 
  rename(PC = CODNUM)


###Agregar el geometry del shape al df de trabajo
codigos$PC <- as.numeric(codigos$PC)
canton2 <- left_join(canton, codigos)


datos3$PC <- as.numeric(datos3$PC)
canton2 <- left_join(canton2, datos3)
canton2 <- canton2[-1,]

canton2 <- canton2[,-ncol(canton2)]


#### Llenar con ceros los canotnes que no presentaron sismos
canton2[is.na(canton2)] <-  0

canton2 <- canton2 %>% 
  dplyr::select(-NCANTON)


### Agregar variables
canton2$clas_n <- car::recode(canton2$mag_prom,
                             "3:3.9999999999999 = 1; 4:4.9=2; 5:5.9=3; 6:6.9=4; 7:7.9=5")
canton2$clas <- as.factor(canton2$clas_n)

levels(canton2$clas) <- c("Micro (< 3)", "Muy ligera (3 a 3.9)", "Ligera (4 a 4.9)", "Moderada (5 a 5.9)")


### Guardar en RDS para facilitar lectura
#saveRDS(canton2, "Data/sismos_geom.RDS")
```


# Análsis descriptivo


```{r}
###Paleta de colores
colors_map <- c("#ffffd4","#fee391", "#fec44f", "#fe9929")
```


```{r}
###Mapa 1
ggplot(canton2$geometry) +
  geom_sf(aes(fill = canton2$cantidad), 
          color = "black",
          linetype = 1,
          lwd = 0.25) +
     scale_fill_gradient2("Cantidad", low = c("#ffffd4", "#fed98e"), mid = "#fe9929", high = c("#d95f0e","#993404"), midpoint = 20, breaks=c(0, 10, 20, 30, 40), limits=c(0,42), labels=c(0, 10, 20, 30, 40)) +
  theme_test() +
  theme(axis.ticks = element_blank(), 
        axis.title = element_blank(), 
        axis.text = element_blank(), 
        panel.grid = element_blank()) +
    theme(legend.text = element_text(size = 9)) 
 

```


```{r}
###Mapa 2
ggplot(canton2$geometry) +
  geom_sf(aes(fill = canton2$clas), 
          color = "black",
          linetype = 1,
          lwd = 0.25)  +
  scale_fill_manual(values = colors_map, name = NULL) +
  theme_test() +
  theme(axis.ticks = element_blank(), 
        axis.title = element_blank(), 
        axis.text = element_blank(), 
        panel.grid = element_blank()) +
    theme(legend.text = element_text(size = 9)) +
  guides(fill=guide_legend(title="Nivel de magnitud"))
 
```



```{r}
datos4 <- datos2 %>% 
  group_by(anio) %>% 
  summarise(cantidad = n(),
            mag_prom = mean(mag))
  
```


```{r}
datos4 <- datos2 %>% 
  separate(
    col = PC,
    sep = c(1),
    into = c("PROV", "c.d"), 
    remove = FALSE
  )

datos4$PROV2 <- as.factor(datos4$PROV)

levels(datos4$PROV2) <- c("San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón")


datos4 <- datos4 %>% 
  group_by(PROV, PROV2) %>% 
  summarise(cantidad = n(),
            mag_prom = mean(mag)) %>% 
  arrange(desc(cantidad))
```


```{r}
### Gráfico 1
ggplot(data=datos4, aes(x=reorder(PROV2, cantidad, FUN = sum), y=cantidad)) +
  geom_col(fill =  "#F1A661") +
    geom_text(aes(label=cantidad),vjust = 0, hjust = -0.1, fontface="bold", size = 3.3) +
    theme_classic() +
    xlab("") +
    ylab("Cantidad") +
    coord_flip() +
  scale_y_continuous(breaks = seq(0, 150, 25), limits = c(0,155), 
                       labels=function(n){format(n, scientific = FALSE)})
```



# Estructura de vecinos y matriz de pesos

```{r}
### Lectura de datos
datos <- readRDS("Datos/sismos_geom.RDS")
```

```{r}
### Datos en formato sp
datos_sp <- as(datos,"Spatial")
```


```{r}
### Cálculo de estructura de vecinos
coords <- coordinates(datos_sp)
id <-row.names(datos_sp) 

nb.1 <- poly2nb(datos_sp,queen = T)
nb.2 <- poly2nb(datos_sp,queen = F)
nb.3 <- knn2nb(knearneigh(coords, k=2), row.names=id)
nb.4 <- knn2nb(knearneigh(coords, k=4), row.names=id)
```


```{r}
### Gráfico 2
par(mfrow = c(2,2))

####Reina
plot(datos_sp, axes=F, border="gray")
plot(nb.1,coords, pch = 20, cex = 0.6, add = T, col = "red")
title("(a) Reina", cex.main= 1)

###Torre
plot(datos_sp, axes=F, border="gray")
plot(nb.2,coords, pch = 20, cex = 0.6, add = T, col = "cyan")
title("(b) Torre", cex.main= 1)

###KNN(2)
plot(datos_sp, axes=F, border="gray")
plot(nb.3,coords, pch = 20, cex = 0.6, add = T, col = "green")
title("(c) KNN(2)", cex.main= 1)

###KNN(4)
plot(datos_sp, axes=F, border="gray")
plot(nb.4,coords, pch = 20, cex = 0.6, add = T, col = "chartreuse3")
title("(d) KNN(4)", cex.main= 1)
```



```{r}
####Matrices de pesos

####Reina
w.11 <- nb2listw(nb.1,style = "W")
w.12 <- nb2listw(nb.1,style = "B")
w.13 <- nb2listw(nb.1,style = "S")

###Torre
w.21 <- nb2listw(nb.2,style = "W")
w.22 <- nb2listw(nb.2,style = "B")
w.23 <- nb2listw(nb.2,style = "S")

###KNN(2)
w.31 <- nb2listw(nb.3,style = "W")
w.32 <- nb2listw(nb.3,style = "B")
w.33 <- nb2listw(nb.3,style = "S")

###KNN(4)
w.41 <- nb2listw(nb.4,style = "W")
w.42 <- nb2listw(nb.4,style = "B")
w.43 <- nb2listw(nb.4,style = "S")


#I de Moran
moran.test(datos_sp$cantidad,listw=w.11)
moran.test(datos_sp$cantidad,listw=w.12)
moran.test(datos_sp$cantidad,listw=w.13)
moran.test(datos_sp$cantidad,listw=w.21)
moran.test(datos_sp$cantidad,listw=w.22)
moran.test(datos_sp$cantidad,listw=w.23)
moran.test(datos_sp$cantidad,listw=w.31)
moran.test(datos_sp$cantidad,listw=w.32)
moran.test(datos_sp$cantidad,listw=w.33)
moran.test(datos_sp$cantidad,listw=w.41)
moran.test(datos_sp$cantidad,listw=w.42)
moran.test(datos_sp$cantidad,listw=w.43)
```



# Análisis de autocorrelación espacial

```{r}
###Leer datos
canton2 <- readRDS("Data/sismos_geom.RDS")
```


```{r}
###Variables de trabajo
map <- canton2
map$vble <- map$cantidad
mapview(map, zcol = "vble")
```


```{r}
# Neighbors
nb <- poly2nb(map, queen = TRUE) # queen shares point or border
nbw <- nb2listw(nb, style = "W")

# Global Moran's I
gmoran <- moran.test(map$vble, nbw,
                     alternative = "greater")
gmoran

gmoran[["estimate"]][["Moran I statistic"]] # Moran's I

gmoran[["statistic"]] # z-score

gmoran[["p.value"]] # p-value
```


```{r}
moran.plot(map$vble, nbw, ylab = "Cantidad espacialmente rezagada", xlab = "Cantidad de sismos", labels=as.character(map$canton), pch=19)
text(35,2, "Alto-Bajo", col = "#4C3F91", font = 2)
text(35,30, "Alto-Alto", col = "#CD5C08", font = 2)
text(1.6,30, "Bajo-Alto", col = "#008170", font = 2)

res_moran <- moran.plot(map$vble, nbw, ylab = "Cantidad espacialmente rezagada", xlab = "Cantidad de sismos", labels=as.character(map$canton), pch=19)
##x son los sismos
##wx son los rezagos
```


```{r}
library(dplyr)
# (-) sismos (+) rezagos

c1.log <- res_moran %>% 
  filter(x < mean(res_moran$x)) %>% 
  filter(wx > mean(res_moran$wx))


#(+) sismos (+) rezagos

c2.log <- res_moran %>% 
  filter(x > mean(res_moran$x)) %>% 
  filter(wx > mean(res_moran$wx))


#(-) sismos (-) rezagos

c3.log <- res_moran %>% 
  filter(x < mean(res_moran$x)) %>% 
  filter(wx < mean(res_moran$wx))


#(+) sismos (-) rezagos

c4.log <- res_moran %>% 
  filter(x > mean(res_moran$x)) %>% 
  filter(wx < mean(res_moran$wx))

```



```{r}
map <- map %>% 
  mutate(c.moran.lag = ifelse(canton %in% c1.log$labels, "Bajo-Alto",
                              ifelse(canton %in% c2.log$labels, "Alto-Alto",
                                     ifelse(canton %in% c3.log$labels, "Bajo-Bajo",
                                            ifelse(canton %in% c4.log$labels, "Alto-Bajo",
                                                   "No")))))
```



```{r}
c1.inf <- c("NANDAYURE", "CORREDORES") #Low-High

c2.inf <- c("SANTA CRUZ", "HOJANCHA", "OSA", "CARRILLO", "QUEPOS", "NICOYA", "GOLFITO") #High-High

c4.inf <- c("GARABITO") #High-Low
```


```{r}
map <- map %>% 
  mutate(c.moran.lag.inf = ifelse(canton %in% c1.inf, "Bajo-Alto",
                              ifelse(canton %in% c2.inf, "Alto-Alto",
                                            ifelse(canton %in% c4.inf, "Alto-Bajo",
                                                   "No influyente"))))

map$c.moran.lag.inf <- as.factor(map$c.moran.lag.inf)

levels(map$c.moran.lag.inf) <- c(levels(map$c.moran.lag.inf), "Bajo-Bajo")

map$c.moran.lag.inf <- ordered(map$c.moran.lag.inf, levels = c("Alto-Alto", "Bajo-Bajo", "Alto-Bajo", "Bajo-Alto", "No influyente"))
```


```{r}
colors_map <- c("#CD5C08", "#4C3F91", "#008170", "#ffffd4")
#colors_map =  c("red",  "lightpink", "skyblue2",  "#ffffd4")
```


```{r}
library(ggplot2)
library(RColorBrewer)
ggplot(map$geometry) +
  geom_sf(aes(fill = map$c.moran.lag.inf), 
          color = "black",
          linetype = 1,
          lwd = 0.25) +
  #scale_fill_brewer(palette="Set3")+
  scale_fill_manual(values = colors_map, name = NULL) +
  theme_test() +
  theme(axis.ticks = element_blank(), 
        axis.title = element_blank(), 
        axis.text = element_blank(), 
        panel.grid = element_blank()) +
    theme(legend.text = element_text(size = 13)) +
  guides(fill=guide_legend(title="Grupos")) +
    theme(legend.title = element_text(size = 15))
 
```





```{r}
lmoran <- localmoran(map$vble, nbw, alternative = "greater")
head(lmoran)
```


```{r}
map$lmI <- lmoran[, "Ii"] # local Moran's I
map$lmZ <- lmoran[, "Z.Ii"] # z-scores
# p-values corresponding to alternative greater
map$lmp <- lmoran[, "Pr(z > E(Ii))"]

p1 <- tm_shape(map) +
  tm_polygons(col = "vble", title = "vble", style = "quantile") +
  tm_layout(legend.outside = TRUE)

p2 <- tm_shape(map) +
  tm_polygons(col = "lmI", title = "I de Moran Local",
              style = "quantile") +
  tm_layout(legend.outside = TRUE, legend.text.size = 1, legend.title.size = 1.4); p2

p3 <- tm_shape(map) +
  tm_polygons(col = "lmZ", title = "Z-score",
              breaks = c(-Inf, 1.65, Inf)) +
  tm_layout(legend.outside = TRUE)

p4 <- tm_shape(map) +
  tm_polygons(col = "lmp", title = "Valores p",
              breaks = c(-Inf, 0.05, Inf), palette = c("#CD5C08", "#ffffd4")) +
  tm_layout(legend.outside = TRUE, legend.text.size = 1, legend.title.size = 1.4); p4



tmap_arrange(p2, p4)
#tmap_arrange(p1, p2, p3, p4)
```


```{r}
local.moral.neg <- map %>% 
  filter(lmI < 0) %>% 
  select(canton, lmI)

local.moral.pos <- map %>% 
  filter(lmI > 0) %>% 
  select(canton, lmI)
```


```{r}
pv.moran <- map %>% 
  filter(lmp < 0.05) %>% 
  select(canton, lmp)
```



```{r}
tm_shape(map) + tm_polygons(col = "lmZ",
title = "Local Moran's I", style = "fixed",
breaks = c(-Inf, -1.96, 1.96, Inf),
labels = c("Negative SAC", "No SAC", "Positive SAC"),
palette =  c("blue", "white", "red")) +
tm_layout(legend.outside = TRUE)
```


Clústers

```{r}
lmoran <- localmoran(map$vble, nbw, alternative = "two.sided")
head(lmoran)
```


```{r}
map$lmp <- lmoran[, 5] # p-values are in column 5
```


```{r}
mp <- moran.plot(as.vector(scale(map$vble)), nbw)
```


```{r}
head(mp)
```


```{r}
map$quadrant <- NA
# high-high
map[(mp$x >= 0 & mp$wx >= 0) & (map$lmp <= 0.05), "quadrant"]<- 1
# low-low
map[(mp$x <= 0 & mp$wx <= 0) & (map$lmp <= 0.05), "quadrant"]<- 2
# high-low
map[(mp$x >= 0 & mp$wx <= 0) & (map$lmp <= 0.05), "quadrant"]<- 3
# low-high
map[(mp$x <= 0 & mp$wx >= 0) & (map$lmp <= 0.05), "quadrant"]<- 4
# non-significant
map[(map$lmp > 0.05), "quadrant"] <- 5
```





```{r}
tm_shape(map) + 
  tm_fill(col = "quadrant", title = "",
breaks = c(1, 2, 3, 4, 5, 6),
palette =  c("red", "blue", "lightpink", "skyblue2", "#ffffd4"),
labels = c("Alto-Alto", "Bajo-Bajo", "Alto-Bajo",
           "Bajo-Alto", "No significativo")) +
tm_legend(text.size = 1)  + tm_borders(alpha = 0.5) +
tm_layout(title = "Conglomerados", legend.outside = TRUE, legend.text.size = 1, legend.title.size = 1.4)
```


